resources:
- repo: self
  clean: true
queue:
  name: Hosted VS2017
steps:
- task: stevedower.python.BuildWheel.BuildWheel@1
  inputs:
    setuppy: 'src/noelbundick/setup.py'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: drop
    publishLocation: Container