on:
  push:
    branches:
      - "*"
    tags:
      - "v*"

env:
  IMAGE: acanthamoeba/azure-cli-extension-noelbundick

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate

        python -m pip install -U pip
        python -m pip install -r requirements.txt
        azdev setup -r .

    - name: Lint code
      run: |
        source .venv/bin/activate

        pylint --disable=fixme src
        flake8 src

    - name: Build extension
      run: |
        source .venv/bin/activate

        azdev extension build noelbundick
        
        WHEEL=$(find ./dist -name "*.whl" -printf "%f")
        echo "::set-env name=WHEEL::$WHEEL"

    - name: Validate extension can be installed
      run: |
        az extension add -s dist/$WHEEL -y
        az extension list

    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

    - id: validate_release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        VERSION=$(echo $WHEEL | grep -Po '\w+-\K(\d+\.*)+')
        if [ "refs/tags/v$VERSION" != "$GITHUB_REF" ]; then
          echo "The source control tag does not match the version specified for the wheel. Did you remember to update setup.py?"
          echo "Tag: $GITHUB_REF"
          echo "Wheel: $VERSION"
          exit 1
        fi

      # TODO: find a replacement action
    - id: create_release
      uses: actions/create-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          ```bash
          az extension add --source https://github.com/noelbundick/azure-cli-extension-noelbundick/releases/download/v${{ env.VERSION }}/${{ env.WHEEL }}
          ```
        draft: true
        prerelease: true

      # TODO: find a replacement action
    - uses: actions/upload-release-asset@v1
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/${{ env.WHEEL }}
        asset_name: ${{ env.WHEEL }}
        asset_content_type: application/zip
